### ISSUE TITLE
Proposal: move samples to subdir

### ISSUE THREAD

**Issue by raburton** [SmingHub/Sming#312] opened 2015-09-30 19:23 UTC
The main Sming folder is cluttered by all the samples. I propose we move them to a subfolder called 'samples'. Comments please...

**Comment by kireevco** [comment] 2015-09-30 19:25
@raburton duplicate of #69 . 
Even more, I think they should move to a separate repo / repos. Please come to #69 for a discussion.

**Closed by kireevco** 2015-09-30 19:25 UTC
