### ISSUE TITLE
Feature Request: Websocket client support

### ISSUE THREAD

**Issue by robotiko** [SmingHub/Sming#164] opened 2015-07-06 11:04 UTC
There are some very useful usages of a Websocket client that would make it an interesting addition. 

Considering the limitations of number of connections accepted in the Websocket server (5 I guess),  there is no way to create a realtime sensor mesh using websockets bigger than that. 

Acting as client, we can have a host acting as a server and clients register from Local wifi  without complex NAT routes, simply connect each device to the server so we can have something similar to HttpClient example but with realtime two way comm with very simple setup.

Also requested in #145

**Comment by ystrem** [comment] 2015-07-06 12:11
+1

-----Original Message-----

**Comment by colinmeikle** [comment] 2015-07-07 20:57
I agree websocket client support would be useful . Note however if you can use standard tcp sockets the TcpClient_NarodMon gives an example of doing this using tcp sockets.

**Comment by kireevco** [comment] 2015-07-07 21:00
My opinion is that TCP has to be improved and be more robust before relying on web socket implementation.

**Comment by hreintke** [comment] 2015-07-07 22:00
@kireevco : If we can instruct all who finds issues on tcp networking to add those to the https://github.com/anakod/Sming/issues/154 then are getting at least an overview of them.
I will be out a couple of days fri-wed but then can have a look on those. 
Of course no guarantee that i actually am able to fix.

**Comment by azmathmoosa** [comment] 2016-02-12 07:34
Has anyone done anything?  Are there any alternatives?!

**Comment by KSDaemon** [comment] 2016-03-16 10:07
Voting for this feature. I'm also seeing interesting use cases for this.

**Comment by hreintke** [comment] 2016-04-22 10:57
Duplicate of #418

**Closed** 2016-04-22 10:58 UTC
Labels: duplicate, enhancement
