### ISSUE TITLE
WebSocketClient connection on own websocket server 

### ISSUE THREAD

**Issue by jgaNet** [SmingHub/Sming#843] opened 2016-12-28 19:51 UTC
Hi,

I'm trying to connect my WebSocket client from ESP8266 to my own Golang Websocket (https://github.com/gorilla/websocket) server through NGINX.

When i tried to connect to  ws://echo.websocket.org it's successful.

But with my own server i have this error :

TcpConnection::staticOnReceive: pbuf is NULL . 

And server side, i can read headers from handshake:

GET / HTTP/1.1
Host: formations.exostic.com
connection: upgrade
x-real-ip: 176.163.68.195
sec-websocket-key:
sec-websocket-protocol: chat
upgrade: websocket
x-nginx-proxy: true
x-forwarded-for: 176.163.68.195
sec-websocket-version: 13

From the server side i have this error : 
upgrade:websocket: key missing or blank

They are no Sec-Websocket-Key inside headers, is it a bug ? 

I don't understand why it's ok for ws://echo.websocket.org but not with mine (I tried an python ws server and an nodejs ws server too but it's the same error);

If you have an available websocket server example, it's welcome. 

Thanks

**Comment by slaff** [comment] 2016-12-29 05:57
@avr39-ripe Can you take a look at this issue?

**Comment by avr39-ripe** [comment] 2016-12-29 09:13
Yes, I will look what is wrong.

**Comment by slaff** [comment] 2017-01-11 19:34
@jgaNet Can you check the latest git version and tell us if the problem is fixed there?

**Comment by slaff** [comment] 2017-02-27 10:38
Feel free to reopen this ticket if the issue is still not fixed in the latest `develop` version.

**Closed by slaff** 2017-02-27 10:38 UTC

**Comment by jgaNet** [comment] 2017-02-27 18:41
Sorry, i didn't have time to check the update but i will do it soon. Thanks
you

*Jérémy Gay*
CEO, Ingénieur-Développeur-Formateur
*Exostic SAS - 95 rue Paul Bellamy - 44000 Nantes*
*06 78 14 96 81* <+33678149681>
*https://exostic.com* <https://exostic.com/>

2017-02-27 11:38 GMT+01:00 slaff <notifications@github.com>:
